# Generated by Django 3.1.3 on 2021-01-02 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('hot', models.CharField(max_length=20)),
                ('img', models.URLField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.content')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=15)),
                ('scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.scene')),
            ],
        ),
    ]
